//! `GET /api/roadmap` — serves the pre-generated roadmap HTML artifact.
//!
//! The artifact lives at `$HOME/lightarchitects/soul/helix/corso/builds/roadmap.html`
//! and is generated by `/SYNC --roadmap`. Returns empty body (→ `empty` state in the
//! frontend) when the file is absent or zero-length. `DOMPurify` sanitization happens
//! client-side; this handler is read-only.

use axum::{
    extract::State,
    http::{StatusCode, header},
    response::IntoResponse,
};

use crate::{auth, server::AppState};

/// Serves the roadmap HTML artifact.
///
/// * `200 text/html` — artifact present and non-empty.
/// * `200` (empty body) — artifact absent or zero-length; frontend shows empty state.
/// * `500` — I/O error reading the artifact.
pub async fn roadmap_handler(
    _: auth::AuthGuard,
    State(state): State<AppState>,
) -> impl IntoResponse {
    let path = state.roadmap_html_path.clone();
    match tokio::fs::read_to_string(&path).await {
        Ok(html) if html.trim().is_empty() => (
            StatusCode::OK,
            [(header::CONTENT_TYPE, "text/plain")],
            String::new(),
        ),
        Ok(html) => (
            StatusCode::OK,
            [(header::CONTENT_TYPE, "text/html; charset=utf-8")],
            html,
        ),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => (
            StatusCode::OK,
            [(header::CONTENT_TYPE, "text/plain")],
            String::new(),
        ),
        Err(_) => (
            StatusCode::INTERNAL_SERVER_ERROR,
            [(header::CONTENT_TYPE, "text/plain")],
            "roadmap artifact unavailable".to_owned(),
        ),
    }
}
