//! HMAC-SHA256 signing and verification for LASDLC hook payloads.
//!
//! Implements Wave 3.2 `cross_repo_ipc_trust.layered_authentication.layer_3`:
//! operator-initiated actions carry HMAC-signed payloads; the gateway verifies
//! before processing. Secret loaded from [`HMAC_SECRET_ENV`].
//!
//! # Security note
//!
//! Rotate `LASDLC_HOOK_HMAC_SECRET` on every gateway deploy. A 32-byte random key
//! generated by `openssl rand -hex 32` is sufficient. Absent secret → all signed
//! payload verification fails with [`SecurityError::SecretNotConfigured`].

use chrono::{DateTime, Utc};
use hmac::{Hmac, Mac};
use serde::{Deserialize, Serialize};
use sha2::Sha256;
use subtle::{Choice, ConstantTimeEq};
use thiserror::Error;

type HmacSha256 = Hmac<Sha256>;

/// Environment variable holding the UTF-8 HMAC shared secret.
pub const HMAC_SECRET_ENV: &str = "LASDLC_HOOK_HMAC_SECRET";

/// Reject payloads whose timestamp is older than this many seconds.
const REPLAY_WINDOW_SECS: i64 = 60;

/// Maximum clock skew: reject payloads timestamped more than this far into the future.
const MAX_FUTURE_SKEW_SECS: i64 = 5;

/// Errors produced by HMAC security operations.
#[derive(Debug, Error)]
pub enum SecurityError {
    /// Payload could not be serialized to its canonical message form.
    #[error("payload serialization failed: {0}")]
    Serialization(#[from] serde_json::Error),
    /// The HMAC secret key has an invalid length (should not occur with byte-slice keys).
    #[error("invalid HMAC key length")]
    InvalidKeyLength,
    /// Timestamp in the payload could not be parsed as RFC 3339.
    #[error("timestamp parse failed: {0}")]
    InvalidTimestamp(String),
    /// Secret env var is absent; configure `LASDLC_HOOK_HMAC_SECRET`.
    #[error("HMAC secret not configured — set {HMAC_SECRET_ENV}")]
    SecretNotConfigured,
}

/// The structured data that travels in an operator-action hook payload.
///
/// Fields must not be reordered — `serde_json::to_string` serializes in struct
/// field order, and the canonical message byte sequence depends on this layout.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HookPayload {
    /// Identifier of the assertion gate being acted upon.
    pub assertion_id: String,
    /// The action being requested (e.g. `provide_citation`, `escalate`).
    pub action_type: String,
    /// Session-bound operator identifier.
    pub operator_id: String,
    /// ISO 8601 / RFC 3339 timestamp at which the payload was created.
    pub timestamp_iso8601: String,
}

/// Load the HMAC secret bytes from the environment variable [`HMAC_SECRET_ENV`].
///
/// # Errors
///
/// Returns [`SecurityError::SecretNotConfigured`] if the variable is absent.
pub fn load_secret() -> Result<Vec<u8>, SecurityError> {
    std::env::var(HMAC_SECRET_ENV)
        .map(std::string::String::into_bytes)
        .map_err(|_| SecurityError::SecretNotConfigured)
}

/// Sign a hook payload and return the lowercase hex-encoded HMAC-SHA256 signature.
///
/// The canonical message is `serde_json::to_string(payload)` — deterministic
/// because `HookPayload` is a plain struct (no map fields with unordered keys).
///
/// # Errors
///
/// Returns [`SecurityError::Serialization`] if serialization fails (should not
/// occur for a well-formed `HookPayload`), or [`SecurityError::InvalidKeyLength`]
/// if `secret` is empty (HMAC-SHA256 accepts any non-empty key).
pub fn sign_hook_payload(payload: &HookPayload, secret: &[u8]) -> Result<String, SecurityError> {
    if secret.is_empty() {
        return Err(SecurityError::InvalidKeyLength);
    }
    let message = serde_json::to_string(payload)?;
    let mut mac =
        HmacSha256::new_from_slice(secret).map_err(|_| SecurityError::InvalidKeyLength)?;
    mac.update(message.as_bytes());
    let result = mac.finalize().into_bytes();
    let mut hex = String::with_capacity(64);
    for b in &result {
        use std::fmt::Write as _;
        let _ = write!(hex, "{b:02x}");
    }
    Ok(hex)
}

/// Verify that `signature` matches the HMAC-SHA256 of `payload` under `secret`.
///
/// Comparison is performed in constant time via [`subtle::ConstantTimeEq`] to
/// prevent timing-oracle attacks.
///
/// Returns `Ok(true)` on valid signature, `Ok(false)` on mismatch.
///
/// # Errors
///
/// Propagates [`SecurityError::Serialization`] or [`SecurityError::InvalidKeyLength`]
/// from [`sign_hook_payload`] if the payload or secret is malformed.
pub fn verify_hook_payload(
    payload: &HookPayload,
    secret: &[u8],
    signature: &str,
) -> Result<bool, SecurityError> {
    let expected = sign_hook_payload(payload, secret)?;
    Ok(ct_eq_bytes(expected.as_bytes(), signature.as_bytes()))
}

/// Returns `Ok(true)` if `timestamp_iso8601` is within the replay window.
///
/// Accepts payloads up to [`REPLAY_WINDOW_SECS`] in the past and up to
/// [`MAX_FUTURE_SKEW_SECS`] in the future (clock-skew tolerance). Rejects
/// anything outside that range to prevent replay and pre-signed payload attacks.
///
/// # Errors
///
/// Returns [`SecurityError::InvalidTimestamp`] if the string is not valid RFC 3339.
pub fn replay_window_check(timestamp_iso8601: &str) -> Result<bool, SecurityError> {
    let ts = timestamp_iso8601
        .parse::<DateTime<Utc>>()
        .map_err(|e| SecurityError::InvalidTimestamp(e.to_string()))?;
    // Positive diff = payload is in the past (normal path).
    // Negative diff = payload is future-dated (allow up to MAX_FUTURE_SKEW_SECS).
    let diff = Utc::now().signed_duration_since(ts).num_seconds();
    Ok((-MAX_FUTURE_SKEW_SECS..=REPLAY_WINDOW_SECS).contains(&diff))
}

/// Constant-time byte slice comparison.
///
/// Never short-circuits on length: an early return on length mismatch would allow
/// an attacker to confirm the expected output length via timing. Instead, length
/// equality is encoded as a `subtle::Choice` and `AND`ed with the content result,
/// so both paths always run the full comparison loop.
///
/// Use this instead of calling `subtle::ConstantTimeEq` directly on `&[u8]` — the
/// blanket impl short-circuits on length, leaking whether the expected length matches.
pub(crate) fn ct_eq_bytes(a: &[u8], b: &[u8]) -> bool {
    let length_eq = Choice::from(u8::from(a.len() == b.len()));
    let min_len = a.len().min(b.len());
    let content_eq = if min_len == 0 {
        Choice::from(1u8)
    } else {
        a[..min_len].ct_eq(&b[..min_len])
    };
    (length_eq & content_eq).into()
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    const TEST_SECRET: &[u8] = b"test-secret-key-32-bytes-padding!";

    fn test_payload() -> HookPayload {
        HookPayload {
            assertion_id: "assert-001".into(),
            action_type: "provide_citation".into(),
            operator_id: "op-kft".into(),
            timestamp_iso8601: Utc::now().to_rfc3339(),
        }
    }

    #[test]
    fn sign_then_verify_roundtrip() {
        let payload = test_payload();
        let sig = sign_hook_payload(&payload, TEST_SECRET).unwrap();
        assert!(verify_hook_payload(&payload, TEST_SECRET, &sig).unwrap());
    }

    #[test]
    fn tampered_payload_fails_verification() {
        let payload = test_payload();
        let sig = sign_hook_payload(&payload, TEST_SECRET).unwrap();
        let mut tampered = payload.clone();
        tampered.action_type = "escalate".into();
        assert!(!verify_hook_payload(&tampered, TEST_SECRET, &sig).unwrap());
    }

    #[test]
    fn wrong_secret_fails_verification() {
        let payload = test_payload();
        let sig = sign_hook_payload(&payload, TEST_SECRET).unwrap();
        assert!(!verify_hook_payload(&payload, b"wrong-secret", &sig).unwrap());
    }

    #[test]
    fn replay_window_accepts_recent_timestamp() {
        let ts = Utc::now().to_rfc3339();
        assert!(replay_window_check(&ts).unwrap());
    }

    #[test]
    fn replay_window_rejects_expired_timestamp() {
        let old = (Utc::now() - chrono::Duration::seconds(120)).to_rfc3339();
        assert!(!replay_window_check(&old).unwrap());
    }

    #[test]
    fn replay_window_rejects_invalid_timestamp() {
        assert!(replay_window_check("not-a-date").is_err());
    }

    #[test]
    fn signature_is_lowercase_hex() {
        let payload = test_payload();
        let sig = sign_hook_payload(&payload, TEST_SECRET).unwrap();
        assert!(
            sig.chars()
                .all(|c| c.is_ascii_hexdigit() && !c.is_uppercase())
        );
        assert_eq!(sig.len(), 64); // SHA-256 = 32 bytes = 64 hex chars
    }

    #[test]
    fn invalid_key_returns_error() {
        let payload = test_payload();
        // Empty slice is the only length HMAC rejects
        let result = sign_hook_payload(&payload, b"");
        assert!(result.is_err());
    }

    /// SERAPH F-MEDIUM-3: `ct_eq_bytes` must not leak via timing side-channel.
    ///
    /// Runs 10 000 iterations of match vs mismatch comparison on equal-length tokens.
    /// The average per-call delta must stay under 100 µs — a coarse smoke test that
    /// catches obvious branching on content equality without relying on sub-ns precision.
    #[test]
    fn ct_eq_bytes_timing_smoke() {
        use std::time::Instant;

        let token_a = b"la_test_admin_token_xxxxxxxxxxxxxxxx";
        let token_b = b"la_test_admin_token_yyyyyyyyyyyyyyyy";
        let iterations = 10_000_usize;

        let t0 = Instant::now();
        for _ in 0..iterations {
            std::hint::black_box(ct_eq_bytes(token_a, token_a));
        }
        let match_ns = t0.elapsed().as_nanos();

        let t1 = Instant::now();
        for _ in 0..iterations {
            std::hint::black_box(ct_eq_bytes(token_a, token_b));
        }
        let mismatch_ns = t1.elapsed().as_nanos();

        let avg_delta_ns = match_ns.abs_diff(mismatch_ns) / iterations as u128;
        assert!(
            avg_delta_ns < 100_000,
            "avg timing delta {avg_delta_ns} ns >= 100 µs — possible timing oracle in ct_eq_bytes"
        );
    }
}
