//! Credential acquisition flow descriptors.
//!
//! Each variant describes a different protocol used to acquire and persist a
//! provider credential.  Route handlers in [`super::routes`] dispatch on the
//! variant to choose the correct auth sequence.

use std::path::PathBuf;

/// Describes how a provider acquires credentials.
///
/// Returned by [`super::ProviderCredentialProvider::credential_flow`].
/// Route handlers pattern-match on the variant to select the correct protocol.
///
/// ## Security notes
/// - `OAuthRedirect`: PKCE and state are generated by the route handler, not
///   the provider — providers only declare the endpoints and scopes.
/// - `CliSubprocess`: `binary` is an absolute `PathBuf`; args are a
///   `Vec<String>` passed directly to `Command::args()`.  This prevents shell
///   injection (Gate 1 F3 amendment — `command: String` was rejected).
#[derive(Debug, Clone)]
pub enum CredentialFlow {
    /// OAuth 2.0 authorization code + PKCE redirect (OA-1, OA-2, OA-5).
    ///
    /// Used by providers that support browser-based consent (e.g. Google).
    OAuthRedirect {
        /// Base authorization endpoint; query params are added by the handler.
        auth_endpoint: &'static str,
        /// OAuth scopes to request, joined with spaces in the URL.
        scopes: &'static [&'static str],
        /// Token exchange endpoint used by the callback handler.
        token_endpoint: &'static str,
    },

    /// RFC 8628 device authorization flow (OA-9).
    ///
    /// Used by providers where the operator authenticates on a separate device
    /// (e.g. GitHub CLI Device Flow).
    DeviceFlow {
        /// `POST` endpoint that returns `device_code` + `user_code`.
        device_code_url: &'static str,
        /// `POST` endpoint polled for the access token.
        poll_url: &'static str,
    },

    /// Static API key entered by the operator (OA-7, OA-8, OA-10).
    ///
    /// Used by providers that issue permanent API keys (Anthropic, `OpenAI`, Mistral).
    /// The key is pasted by the operator and stored in the Keychain — never logged.
    ApiKey {
        /// User-facing prompt shown in the `ApiKeyInputModal` component.
        prompt: &'static str,
    },

    /// CLI subprocess credential acquisition.
    ///
    /// Used for providers whose CLI handles authentication locally (e.g. Ollama).
    /// Structured args prevent shell injection; `binary` is an absolute path.
    CliSubprocess {
        /// Absolute path to the binary passed to `Command::new()`.
        binary: PathBuf,
        /// Arguments passed directly to `Command::args()` — never shell-interpolated.
        args: Vec<String>,
    },
}
