//! Google OAuth 2.0 PKCE credential provider.
//!
//! Implements [`ProviderCredentialProvider`] for Google accounts.
//! The refresh token is stored exclusively in the macOS Keychain (OA-3, OA-12).
//!
//! Security properties:
//! - OA-1: PKCE S256 challenge generated by [`super::pkce::generate_pkce_pair`].
//! - OA-3 / OA-12: Only the refresh token is persisted; stored via Keychain subprocess.
//! - OA-5: `redirect_uri` is locked to `http://127.0.0.1:{port}/api/auth/credential/google/callback` by the route handler.
//! - OA-7: Credentials never written to logs.

use anyhow::Result;

use super::{CredentialFlow, ProviderCredentialProvider, keychain};

/// macOS Keychain service name for the Google refresh token (OA-3).
pub const KEYCHAIN_SERVICE: &str = "la-google-credential";

/// Google OIDC authorization endpoint.
pub const AUTH_ENDPOINT: &str = "https://accounts.google.com/o/oauth2/v2/auth";

/// Google OAuth token exchange endpoint.
pub const TOKEN_ENDPOINT: &str = "https://oauth2.googleapis.com/token";

/// Minimum scopes (OA-6 qualifier: standard OIDC protocol providers only).
///
/// `cloud-platform` gives access to GCP APIs (Vertex AI, Gen App Builder).
/// `openid` + `email` are standard OIDC claims.
pub const SCOPES: &[&str] = &[
    "openid",
    "email",
    "https://www.googleapis.com/auth/cloud-platform",
];

/// Google credential provider.
///
/// Stateless — all mutable state lives in `AppState::oauth_states` during the
/// in-flight OAuth handshake and in the macOS Keychain after completion.
pub struct GoogleCredentialProvider;

impl ProviderCredentialProvider for GoogleCredentialProvider {
    fn provider_id(&self) -> &'static str {
        "google"
    }

    fn credential_flow(&self) -> Result<CredentialFlow> {
        Ok(CredentialFlow::OAuthRedirect {
            auth_endpoint: AUTH_ENDPOINT,
            scopes: SCOPES,
            token_endpoint: TOKEN_ENDPOINT,
        })
    }

    fn store_credential(&self, secret: &str) -> Result<()> {
        keychain::keychain_set(KEYCHAIN_SERVICE, secret)
    }

    fn load_credential(&self) -> Result<Option<String>> {
        keychain::keychain_get(KEYCHAIN_SERVICE)
    }

    fn revoke_credential(&self) -> Result<()> {
        keychain::keychain_delete(KEYCHAIN_SERVICE)
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn provider_id_is_google() {
        assert_eq!(GoogleCredentialProvider.provider_id(), "google");
    }

    #[test]
    fn credential_flow_is_oauth_redirect() {
        let flow = GoogleCredentialProvider.credential_flow().unwrap();
        assert!(
            matches!(flow, CredentialFlow::OAuthRedirect { .. }),
            "Google must use the OAuthRedirect flow"
        );
    }

    #[test]
    fn auth_endpoint_is_google_accounts() {
        let flow = GoogleCredentialProvider.credential_flow().unwrap();
        if let CredentialFlow::OAuthRedirect { auth_endpoint, .. } = flow {
            assert!(
                auth_endpoint.starts_with("https://accounts.google.com/"),
                "auth endpoint must be accounts.google.com, got: {auth_endpoint}"
            );
        }
    }

    #[test]
    fn scopes_include_cloud_platform() {
        assert!(
            SCOPES.iter().any(|s| s.contains("cloud-platform")),
            "scopes must include cloud-platform for GCP access"
        );
    }
}
