//! Agent protocol types — SSE streaming + WebSocket control.
//!
//! Mirrors the `lightarchitects-cli` `AgentEvent` union for wire serialization.
//! Every variant maps to a distinct SSE `event:` name so the browser can
//! dispatch without parsing the full JSON body.
//!
//! ## Transport mapping
//!
//! | Direction | Transport | Message |
//! |-----------|-----------|---------|
//! | Server → Browser | SSE | `AgentEvent` |
//! | Browser → Server | WebSocket | `ControlMessage` |
//! | Server → Browser | WebSocket | `ControlResponse` |
//!
//! ## SSE event names
//!
//! The `event:` field on each SSE line is the `snake_case` variant name:
//! `text`, `tool_start`, `tool_complete`, `complete`, `error`, etc.

use serde::{Deserialize, Serialize};

/// One event emitted by the agent runner during a turn.
///
/// Serialised to SSE as:
/// ```text
/// event: tool_start
/// id: {build_id}-{sequence}
/// data: {"type":"tool_start","name":"Read","id":"call_01","input":{...}}
/// ```
///
/// This enum is a wire-compatible subset of the `lightarchitects-cli`
/// `AgentEvent`.  As the CLI adds new event types, they should be mirrored
/// here with the same field names so NDJSON parsing is zero-config.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AgentEvent {
    // ── Core streaming ─────────────────────────────────────────────────────────
    /// Streaming text chunk from the LLM.
    Text {
        /// Text content generated by the LLM.
        chunk: String,
    },

    /// Thinking / reasoning content from the LLM.
    Thinking {
        /// Reasoning content (e.g. chain-of-thought).
        content: String,
    },

    /// A tool call has been parsed from the LLM response and is about to execute.
    ToolStart {
        /// Tool name (e.g. "Read", "Write", "Bash").
        name: String,
        /// Tool call ID from the LLM.
        id: String,
        /// Tool invocation arguments.
        input: serde_json::Value,
    },

    /// A tool call finished executing.
    ToolComplete {
        /// Tool call ID matching the `ToolStart`.
        id: String,
        /// Whether execution succeeded.
        success: bool,
        /// Wall-clock duration in milliseconds.
        duration_ms: u64,
        /// Tool result text (stdout, file content, etc.).
        #[serde(skip_serializing_if = "Option::is_none")]
        result: Option<String>,
    },

    /// The agent turn completed successfully.
    Complete {
        /// Why the loop stopped.
        reason: TerminationReason,
    },

    /// A non-fatal error occurred during the turn.
    Error {
        /// Human-readable error message.
        message: String,
        /// Whether the runner can continue after this error.
        #[serde(skip_serializing_if = "Option::is_none")]
        recoverable: Option<bool>,
    },

    /// Token usage for the turn (or cumulative).
    TokenUsage {
        /// Input / prompt tokens consumed.
        input: u64,
        /// Output / completion tokens generated.
        output: u64,
    },

    /// Status bar update (e.g. "compacting...", "compacted: 12 turns → 1").
    StatusUpdate {
        /// Human-readable status text.
        text: String,
    },

    // ── Phase 5 TRUST hook events ─────────────────────────────────────────────
    /// PICK classification result for the current task.
    PickClassified {
        /// Resolved execution mode.
        mode: ExecutionMode,
    },

    /// DISCOVER context was injected before the first LLM call.
    DiscoverInjected {
        /// Number of helix entries retrieved.
        entry_count: usize,
        /// Total characters injected into context.
        chars_injected: usize,
    },

    /// VERIFY gate completed (passed).
    VerifyComplete {
        /// Whether verification passed.
        passed: bool,
        /// How many retry attempts were used.
        retries_used: u8,
    },

    /// VERIFY gate exhausted all retries without passing.
    VerifyFailed {
        /// Human-readable failure reason.
        reason: String,
    },

    /// REFLECT call completed.
    ReflectComplete {
        /// Significance score (0.0–1.0).
        significance: f64,
        /// Whether enrichment was triggered.
        enrich_triggered: bool,
    },

    /// Cost gate triggered — awaiting user approval.
    CostGateCheck {
        /// Projected total cost in USD.
        projected_usd: f64,
        /// Configured cost gate in USD.
        gate_usd: f64,
    },

    // ── Phase 10+ advanced events ─────────────────────────────────────────────
    /// Squad preset suggestion from lifecycle engine.
    SquadSuggestion {
        /// Preset name (e.g. "review", "security", "deploy").
        preset: String,
        /// Why this preset was suggested.
        reason: String,
    },

    /// Strand resonance bump after tool completion.
    StrandBump {
        /// Strand index (0=Analytical, 1=Precision, 2=Architectural,
        /// 3=Collaborative, 4=Methodical, 5=Contextual, 6=Candid).
        strand: u8,
        /// Bump magnitude (typically 0.05–0.10).
        delta: f32,
    },

    /// Security policy violation (sandbox escape, path traversal).
    SecurityViolation {
        /// Event classification (e.g. `path_traversal`).
        event_type: String,
        /// Tool that triggered the violation.
        tool: String,
        /// Affected path, if any.
        #[serde(skip_serializing_if = "Option::is_none")]
        path: Option<String>,
        /// Detailed description of the violation.
        detail: String,
    },

    /// Sandbox blocked a tool operation.
    SandboxBlocked {
        /// Tool that was blocked.
        tool: String,
        /// Path the tool attempted to access.
        attempted_path: String,
        /// Why the operation was blocked.
        reason: String,
    },

    /// Resource limit hit during tool execution.
    ResourceLimitHit {
        /// Tool that hit the limit.
        tool: String,
        /// Type of limit (e.g. "disk", "memory", "time").
        limit_type: String,
        /// Actual value measured.
        value: u64,
        /// Configured maximum.
        max: u64,
    },

    /// Exec-server health status.
    ExecServerStatus {
        /// Whether the exec server is reachable.
        connected: bool,
        /// Process ID, if known.
        #[serde(skip_serializing_if = "Option::is_none")]
        pid: Option<u32>,
    },

    /// LLM provider switched mid-session (rate-limit fallback).
    ProviderFallback {
        /// Provider that was rate-limited.
        from: String,
        /// Provider now being used.
        to: String,
    },

    // ── Phase 11 lens system ───────────────────────────────────────────────────
    /// Lens selection completed.
    LensesSelected {
        /// Sibling names selected (e.g. `["SOUL", "SERAPH", "CORSO"]`).
        lenses: Vec<String>,
        /// Tier at which lenses will fire (1 = static, 2 = MCP, 3 = LLM).
        tier: u8,
    },

    /// Single lens assessment completed.
    LensAssessment {
        /// Sibling name (e.g. `"SERAPH"`).
        sibling: String,
        /// Tier of assessment that produced this finding.
        tier: u8,
        /// One-sentence finding, or `None` if the lens found nothing relevant.
        #[serde(skip_serializing_if = "Option::is_none")]
        finding: Option<String>,
        /// Confidence 0.0–1.0.
        confidence: f64,
    },

    // ── Phase 14 child agent events ──────────────────────────────────────────
    /// Child agent was forked.
    ChildAgentForked {
        /// Display name of the child agent.
        child_name: String,
        /// Task ID assigned to the child.
        task_id: String,
        /// Working directory (worktree path if isolated).
        cwd: String,
    },

    /// Child agent completed.
    ChildAgentCompleted {
        /// Display name of the child agent.
        child_name: String,
        /// Task ID of the child.
        task_id: String,
        /// Whether the child completed successfully.
        success: bool,
        /// Summary output from the child.
        summary: String,
    },

    // ── Plan mode ──────────────────────────────────────────────────────────────
    /// Plan mode queue is ready for operator review.
    PlanQueueReady {
        /// Queued actions awaiting approval.
        actions: Vec<QueuedAction>,
    },

    // ── Heartbeat ─────────────────────────────────────────────────────────────
    /// Heartbeat / keepalive emitted every ~30s during long turns.
    Heartbeat,
}

impl AgentEvent {
    /// SSE `event:` name for this variant.
    pub fn event_name(&self) -> &'static str {
        match self {
            Self::Text { .. } => "text",
            Self::Thinking { .. } => "thinking",
            Self::ToolStart { .. } => "tool_start",
            Self::ToolComplete { .. } => "tool_complete",
            Self::Complete { .. } => "complete",
            Self::Error { .. } => "error",
            Self::TokenUsage { .. } => "token_usage",
            Self::StatusUpdate { .. } => "status_update",
            Self::PickClassified { .. } => "pick",
            Self::DiscoverInjected { .. } => "discover",
            Self::VerifyComplete { .. } => "verify",
            Self::VerifyFailed { .. } => "verify_failed",
            Self::ReflectComplete { .. } => "reflect",
            Self::CostGateCheck { .. } => "cost_gate",
            Self::SquadSuggestion { .. } => "squad_suggestion",
            Self::StrandBump { .. } => "strand_bump",
            Self::SecurityViolation { .. } => "security_violation",
            Self::SandboxBlocked { .. } => "sandbox_blocked",
            Self::ResourceLimitHit { .. } => "resource_limit",
            Self::ExecServerStatus { .. } => "exec_server_status",
            Self::ProviderFallback { .. } => "provider_fallback",
            Self::LensesSelected { .. } => "lenses_selected",
            Self::LensAssessment { .. } => "lens_assessment",
            Self::ChildAgentForked { .. } => "child_forked",
            Self::ChildAgentCompleted { .. } => "child_complete",
            Self::PlanQueueReady { .. } => "plan_queue",
            Self::Heartbeat => "heartbeat",
        }
    }
}

/// Why the agent loop terminated.
///
/// Mirrors `lightarchitects-cli::agent::TerminationReason`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "kind")]
pub enum TerminationReason {
    /// Normal completion — LLM returned text with no tool calls.
    Complete,
    /// Iteration cap reached.
    MaxIterations,
    /// Token budget exhausted.
    TokenBudgetExhausted,
    /// User cancelled (e.g. cost gate denied).
    UserCancelled,
    /// Wall-clock timeout exceeded.
    Timeout,
    /// Unrecoverable error during execution.
    Error {
        /// Error message.
        message: String,
    },
    /// VERIFY hook exhausted all retries without passing.
    VerifyExhausted,
}

/// PICK classification modes.
///
/// Mirrors `lightarchitects-cli::agent::pick::ExecutionMode`.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ExecutionMode {
    /// Read-only / explain task. No `TRIUNE_THOUGHT`. No `VERIFY`.
    Solo,
    /// Write/edit task. Adds `TRIUNE_THOUGHT` injection + `VERIFY`.
    SoloWithVerify,
    /// Complex multi-sibling task. Full hook pipeline.
    Squad,
}

/// One queued action in plan mode.
///
/// Mirrors `lightarchitects-cli::tui::plan_mode::QueuedAction`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QueuedAction {
    /// Tool name (e.g. "Write", "Edit", "Bash").
    pub tool: String,
    /// Primary target — file path for Write/Edit, command for Bash.
    pub target: String,
    /// Human-readable summary shown in the approval panel.
    pub preview: String,
    /// Original tool invocation arguments.
    pub args: serde_json::Value,
    /// Tool call ID from the LLM.
    pub tool_call_id: String,
}

// ── WebSocket control messages (browser → server) ───────────────────────────

/// Control message sent by the browser over the agent WebSocket.
///
/// Patterned after Codex CLI's control protocol (JSON-RPC-lite semantics
/// but simplified for single-connection webshell use).
#[derive(Debug, Clone, Deserialize)]
#[serde(tag = "action", rename_all = "snake_case")]
pub enum ControlMessage {
    /// Start a new turn with the given user message.
    ///
    /// Equivalent to Codex `turn/start`.
    SendMessage {
        /// User message text.
        text: String,
    },

    /// Approve a pending permission request.
    ApprovePermission {
        /// Permission request ID from the `PermissionRequest` event.
        request_id: String,
    },

    /// Deny a pending permission request.
    DenyPermission {
        /// Permission request ID from the `PermissionRequest` event.
        request_id: String,
        /// Optional reason for denial.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        reason: Option<String>,
    },

    /// Interrupt / cancel the current in-flight turn.
    ///
    /// Equivalent to Codex `turn/interrupt`.
    Interrupt,

    /// Steer the agent mid-turn (append additional instructions).
    ///
    /// Equivalent to Codex `turn/steer`.
    Steer {
        /// Additional instructions to append.
        text: String,
    },

    /// Override the system prompt preamble for subsequent turns.
    ///
    /// Must be sent before `SendMessage`. Validated on the gateway side
    /// (≤ 8 KiB, no NUL bytes). The browser can issue this to inject
    /// a Governor or Worker role prompt before the first turn.
    SetSystemPrompt {
        /// New system prompt preamble text.
        text: String,
    },

    /// Request the current plan queue be executed.
    ExecutePlan,

    /// Ping / keepalive from the browser.
    Ping,
}

/// Response sent by the server over the agent WebSocket.
///
/// Every control message gets an `Ack` or `Reject`.  Asynchronous events
/// (permission resolved, interrupted) arrive independently.
#[derive(Debug, Clone, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ControlResponse {
    /// The control action was accepted.
    Ack {
        /// Action name that was acknowledged.
        action: String,
    },

    /// The control action was rejected with a reason.
    Reject {
        /// Action name that was rejected.
        action: String,
        /// Human-readable rejection reason.
        reason: String,
    },

    /// A permission was resolved (approved or denied).
    PermissionResolved {
        /// Permission request ID.
        request_id: String,
        /// Whether the permission was approved.
        approved: bool,
    },

    /// The current turn was interrupted.
    Interrupted,

    /// Pong reply to browser Ping.
    Pong,

    /// Server-side error.
    ServerError {
        /// Error message.
        message: String,
    },
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::manual_string_new)]
mod tests {
    use super::*;

    #[test]
    fn agent_event_serialisation_roundtrip() {
        let ev = AgentEvent::Text {
            chunk: "hello".to_owned(),
        };
        let json = serde_json::to_string(&ev).unwrap();
        assert_eq!(json, r#"{"type":"text","chunk":"hello"}"#);
        let parsed: AgentEvent = serde_json::from_str(&json).unwrap();
        assert!(matches!(parsed, AgentEvent::Text { chunk } if chunk == "hello"));
    }

    #[test]
    fn control_message_deserialisation() {
        let json = r#"{"action":"send_message","text":"hi"}"#;
        let msg: ControlMessage = serde_json::from_str(json).unwrap();
        assert!(matches!(msg, ControlMessage::SendMessage { text } if text == "hi"));
    }

    #[test]
    fn control_response_serialisation() {
        let resp = ControlResponse::Ack {
            action: "ping".to_owned(),
        };
        let json = serde_json::to_string(&resp).unwrap();
        assert_eq!(json, r#"{"type":"ack","action":"ping"}"#);
    }

    #[test]
    fn event_name_matches_variant() {
        assert_eq!(
            AgentEvent::Text {
                chunk: String::new()
            }
            .event_name(),
            "text"
        );
        assert_eq!(
            AgentEvent::ToolStart {
                name: String::new(),
                id: String::new(),
                input: serde_json::Value::Null
            }
            .event_name(),
            "tool_start"
        );
        assert_eq!(
            AgentEvent::Complete {
                reason: TerminationReason::Complete
            }
            .event_name(),
            "complete"
        );
    }
}
