//! Semantic-convention constants for `helix::generation` AYIN spans.
//!
//! All span names use the `helix.generation.*` namespace. All attribute keys
//! use the same namespace as a prefix so AYIN's lineage circuit and analytics
//! can filter on `helix.generation.*` to surface only RAG-pipeline activity.

// ── Span names ────────────────────────────────────────────────────────────────

/// `LlmCompleter::complete` call (one HTTP round-trip to the LLM provider).
pub const SPAN_GENERATION_COMPLETE: &str = "helix.generation.complete";

/// Parent span wrapping a full retrieval-augmented generation pipeline
/// (classify → retrieve → complete). Children include
/// [`SPAN_GENERATION_COMPLETE`] and any helix retrieval spans.
pub const SPAN_GENERATION_RAG_PIPELINE: &str = "helix.generation.rag_pipeline";

// ── Attribute keys ────────────────────────────────────────────────────────────

/// `QuestionIntent` variant that drove strategy / prompt selection.
/// Values: `"literal" | "preference" | "temporal" | "counting" | "abstention"`.
pub const ATTR_GENERATION_INTENT: &str = "helix.generation.intent";

/// `ContextStrategy` chosen by the router.
/// Values: `"ranked" | "full_context"`.
pub const ATTR_GENERATION_STRATEGY: &str = "helix.generation.strategy";

/// `ModelClass` declared by the completer.
/// Values: `"frontier" | "mid_tier" | "cheap"`.
pub const ATTR_GENERATION_MODEL_CLASS: &str = "helix.generation.model_class";

/// Stable provider identifier from `LlmCompleter::name`
/// (e.g. `"anthropic:claude-sonnet-4-6"`).
pub const ATTR_GENERATION_PROVIDER: &str = "helix.generation.provider";

/// Bare model string passed to the provider (e.g. `"claude-sonnet-4-6"`,
/// `"qwen2.5:32b"`). Useful for filtering in AYIN analytics.
pub const ATTR_GENERATION_MODEL: &str = "helix.generation.model";

/// Input tokens consumed by the LLM call, as reported by the provider.
/// May be `0` if the provider does not return token counts.
pub const ATTR_GENERATION_INPUT_TOKENS: &str = "helix.generation.input_tokens";

/// Output tokens generated by the LLM call, as reported by the provider.
pub const ATTR_GENERATION_OUTPUT_TOKENS: &str = "helix.generation.output_tokens";

/// Wall-clock latency of the HTTP completion request in milliseconds.
pub const ATTR_GENERATION_LATENCY_MS: &str = "helix.generation.latency_ms";

/// Character length of the system prompt sent to the provider.
pub const ATTR_GENERATION_SYSTEM_CHARS: &str = "helix.generation.system_chars";

/// Character length of the user prompt sent to the provider.
pub const ATTR_GENERATION_USER_CHARS: &str = "helix.generation.user_chars";

/// Character length of the generated completion text.
pub const ATTR_GENERATION_OUTPUT_CHARS: &str = "helix.generation.output_chars";

/// Classification of any error returned to the caller. One of:
/// `"http" | "auth" | "empty" | "timeout" | "provider" | "serde" | "missing_credential"`.
/// Absent on successful completions.
pub const ATTR_GENERATION_ERROR_KIND: &str = "helix.generation.error_kind";

// ── DecisionPoint label conventions ───────────────────────────────────────────

/// `DecisionPoint::name` value emitted on the RAG pipeline span when the
/// classifier picks an intent.
pub const DECISION_INTENT_CLASSIFIED: &str = "intent_classified";

/// `DecisionPoint::name` value emitted on the RAG pipeline span when the
/// router picks a context strategy.
pub const DECISION_STRATEGY_SELECTED: &str = "strategy_selected";
