//! HTML footer — generation metadata.

/// Renders the document `<footer>` element.
#[must_use]
pub fn render(skeleton_only: bool) -> String {
    let mode = if skeleton_only { "skeleton" } else { "full" };
    format!(
        "<footer>\n  <p>Generated by <strong>lightarchitects-arch</strong> &mdash; mode: {mode}</p>\n</footer>\n"
    )
}
